INSERT INTO public.site_settings (
  id, institute_name, site_logo_base64,
  hero_headline, hero_subtext, hero_cta_text,
  about_story, about_mission, about_vision, about_values,
  contact_address, contact_phone_1, contact_phone_2,
  contact_email, contact_working_hours,
  google_map_embed_url,
  social_facebook, social_instagram, social_youtube, social_linkedin,
  whatsapp_number,
  meta_title, meta_description,
  hero_bg_image, about_image, contact_image,
  popup_enabled, popup_image_base64, popup_title, popup_link
) VALUES (
  'default',
  'Skyline Institute',
  '',
  'Crafting Professional Bartenders & Hospitality Leaders',
  'Learn from international flair champions. Get certified practical training in bar mechanics, mixology, barista latte art, and secure direct placements in 5-star luxury hotels.',
  'Explore Courses',
  'Skyline Institute is Khatima''s premier vocational academy specialized in professional bartending, mixology, flair art, and barista hospitality. Established with a single goal of bridging the skill gap, we guide students with hands-on labs.',
  'To provide top-tier industry-aligned vocational skills to aspiring students, empowering them with absolute technical proficiency and securing their professional careers.',
  'To be recognized globally as the finest standard for practical training in bartending and hospitality, fostering innovation, master craft, and professional values.',
  'Excellence in Craftsmanship, Direct Industry Placement, Inclusivity, Continuous Skill Innovation, and Student-First Support.',
  'Sitarganj Road, Near Bus Station, Khatima, Udham Singh Nagar, Uttarakhand 262308',
  '+919557795551',
  '+916395427119',
  'admissions@skylineinstitute.in',
  'Mon - Sat: 9:00 AM - 6:00 PM (Sunday Closed)',
  'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3509.302194639981!2d79.967812!3d28.92212!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x39a0fa3a19bffffff%3A0x334bf4ffb8a7c2f0!2sKhatima%2C%20Uttarakhand!5e0!3m2!1sen!2sin!4v1620000000000',
  'https://facebook.com/skylineinstitute',
  'https://instagram.com/skylineinstitute',
  'https://youtube.com/skylineinstitute',
  'https://linkedin.com/company/skylineinstitute',
  '+919557795551',
  'Skyline Institute | Leading Bartending & Hospitality School',
  'Master Mixology, Flair Bartending, and Latte Art at Khatima''s top vocational school. 100% Practical training labs and guaranteed hotel placement.',
  '', '', '',
  false, '', 'Admissions Open for New Bartending & Barista Batches!', '#enquiry'
)
ON CONFLICT (id) DO UPDATE SET
  institute_name = EXCLUDED.institute_name,
  site_logo_base64 = EXCLUDED.site_logo_base64,
  hero_headline = EXCLUDED.hero_headline,
  hero_subtext = EXCLUDED.hero_subtext,
  hero_cta_text = EXCLUDED.hero_cta_text,
  about_story = EXCLUDED.about_story,
  about_mission = EXCLUDED.about_mission,
  about_vision = EXCLUDED.about_vision,
  about_values = EXCLUDED.about_values,
  contact_address = EXCLUDED.contact_address,
  contact_phone_1 = EXCLUDED.contact_phone_1,
  contact_phone_2 = EXCLUDED.contact_phone_2,
  contact_email = EXCLUDED.contact_email,
  contact_working_hours = EXCLUDED.contact_working_hours,
  google_map_embed_url = EXCLUDED.google_map_embed_url,
  social_facebook = EXCLUDED.social_facebook,
  social_instagram = EXCLUDED.social_instagram,
  social_youtube = EXCLUDED.social_youtube,
  social_linkedin = EXCLUDED.social_linkedin,
  whatsapp_number = EXCLUDED.whatsapp_number,
  meta_title = EXCLUDED.meta_title,
  meta_description = EXCLUDED.meta_description,
  hero_bg_image = EXCLUDED.hero_bg_image,
  about_image = EXCLUDED.about_image,
  contact_image = EXCLUDED.contact_image,
  popup_enabled = EXCLUDED.popup_enabled,
  popup_image_base64 = EXCLUDED.popup_image_base64,
  popup_title = EXCLUDED.popup_title,
  popup_link = EXCLUDED.popup_link;